version_esquema: 1
mapa_predeterminado: osm
mapas:
  - id: osm
    nombre: Estándar
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    atribucion: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    zoom_minimo: 1
    zoom_maximo: 19
  - id: satelite
    nombre: Satélite 2025
    url: https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless-2025_3857/default/g/{z}/{y}/{x}.jpg
    atribucion: '<a href="https://cloudless.eox.at/">EOxCloudless</a> by EOX IT Services GmbH (Contains modified Copernicus Sentinel data 2025)'
    zoom_minimo: 1
    zoom_maximo: 19
    zoom_nativo_maximo: 14
  - id: topografico
    nombre: Topográfico
    url: https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png
    atribucion: 'Map data: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, SRTM | Map style: &copy; <a href="https://opentopomap.org/">OpenTopoMap</a> (<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA</a>)'
    zoom_minimo: 1
    zoom_maximo: 19
    zoom_nativo_maximo: 17
